ORG 1000H
 MAYUSCULAS DB 40H
 FIN DB ?
 MINUSCULAS DB 60H
 FIN2 DB ?
 CONT DB 26
ORG 2000H ;
 
 LOOP: INC MAYUSCULAS
 INC MINUSCULAS
 MOV BX, OFFSET MAYUSCULAS
 MOV AL, OFFSET FIN - OFFSET MAYUSCULAS
 INT 7    
 MOV BX, OFFSET MINUSCULAS
 MOV AL, OFFSET FIN2 - OFFSET MINUSCULAS
 INT 7  
 DEC CONT 
 JNZ LOOP
 INT 0
END
