ORG 1000H
 TAM_CLAVE DW 4
 MSJ DB "INGRESE SU CLAVE"
 MSJ_FIN DB ?
 MSJ_PERMITIDO DB 0AH
               DB "ACCESO PERMITIDO"
 MSJ_DENEGADO DB 0AH
              DB "ACCESO DENEGADO"
         
 MSJ_DENEGADO_FIN DB ?
 CLAVE_BASE DB "COSA"
 
ORG 1500H
 CLAVE_INGRESADA DB ?
 
ORG 3000H
LEER_CLAVE: MOV BX, OFFSET MSJ
 MOV AL, OFFSET MSJ_FIN-OFFSET MSJ
 INT 7
 MOV CX, 0
 MOV BX, OFFSET CLAVE_INGRESADA
 ITERAR: CMP CX, TAM_CLAVE
 JZ LEER_CLAVE_FIN
 INT 6
 INC BX
 INC CX
 JMP ITERAR
LEER_CLAVE_FIN:RET
 
VERIFICAR_CLAVE: MOV CL,0
 MOV DX, TAM_CLAVE
 DEC DX
REVISAR: CMP CX, DX
 JZ VALIDO
 MOV BX, OFFSET CLAVE_INGRESADA
 ADD BX, CX
 MOV AL, [BX]
 MOV BX, OFFSET CLAVE_BASE
 ADD BX, CX
 INC CL
 CMP AL, [BX]
 JZ REVISAR
 
INVALIDO: MOV BX, OFFSET MSJ_DENEGADO
 MOV AL, OFFSET MSJ_DENEGADO_FIN-OFFSET MSG_DENEGADO
 INT 7
 JMP VERIFICAR_CLAVE_FIN
VALIDO: MOV BX, OFFSET MSJ_PERMITIDO
 MOV AL, OFFSET MSJ_DENEGADO-OFFSET MSJ_PERMITIDO
 INT 7
 VERIFICAR_CLAVE_FIN:RET
 
ORG 2000H
 CALL LEER_CLAVE
 CALL VERIFICAR_CLAVE
 INT 0
END